# Generated by Django 4.1.8 on 2024-03-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblequiz', '0002_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idTransaction',
            field=models.CharField(default='', max_length=100),
        ),
    ]
