# Generated by Django 4.1.8 on 2024-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblequiz', '0004_userquestionhistory_date_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionhistory',
            name='is_affiche',
            field=models.BooleanField(default=False),
        ),
    ]
