# Generated by Django 4.1.8 on 2024-03-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblequiz', '0008_badge_userprofile_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
