# Generated by Django 4.1.8 on 2024-06-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblequiz', '0009_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_indicatif',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
